spring.application.name=user
server.port=8081

# Configuração do Banco de Dados fou-db
spring.datasource.url=jdbc:postgresql://localhost:5432/fou-db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do Hibernate (Cria a tabela 'user' automaticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# IMPORTANTE: 'user' é uma palavra reservada no Postgres.
# Isso força o Hibernate a usar aspas na tabela, ex: "user"
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
