spring.application.name=email-service
server.port=8082

# Nome da fila (usado no Config e no Consumer)
spring.rabbitmq.queue=email-queue

# Configuracao RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Configuracao SMTP (Gmail Exemplo)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=seu-email@gmail.com
spring.mail.password=sua-senha-de-app
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true