server.port=8083
spring.application.name=auth
spring.datasource.url=jdbc:postgresql://localhost:5432/fou-db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

jwt.secret=5367123709859703373367639792F423F452842947D6251655468576D5A71347437
jwt.expiration=86400000